//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACTIKA1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUYERS
    {
        public int ID_BUYERS { get; set; }
        public Nullable<int> ID_EMPLOYEE { get; set; }
        public Nullable<int> ID_BLINI { get; set; }
    
        public virtual BLINI BLINI { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
