//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACTIKA1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TEREMOKEntities3 : DbContext
    {
        public TEREMOKEntities3()
            : base("name=TEREMOKEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BLINI> BLINI { get; set; }
        public virtual DbSet<BUYERS> BUYERS { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEE { get; set; }
    }
}
